apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    signingConfigs {
        config {
            keyAlias 'lokuphone'
            keyPassword 'freezer@123'
            storeFile file('C:/gigs/TimeFreezer/keyfreezer.jks')
            storePassword 'freezer@123'
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    defaultConfig {
        applicationId "com.time.freezer"
        minSdkVersion 24
        compileSdk 36
        targetSdkVersion 36
        versionCode 42
        versionName "4.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.config
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    namespace 'com.time.freezer'
    compileSdk 36
    ndkVersion '27.0.12077973'
}

dependencies {
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    def billing_version = "9.1.0"

    implementation "com.android.billingclient:billing:$billing_version"

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'

    implementation "androidx.fragment:fragment-ktx:1.9.1"
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'de.hdodenhof:circleimageview:3.1.0'

    implementation "androidx.core:core-ktx:1.16.0"
    implementation 'io.reactivex.rxjava3:rxjava:3.1.12'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    def camerax_version = "1.5.3"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"
    implementation "androidx.camera:camera-lifecycle:$camerax_version"
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:13.0.0'
    implementation 'com.google.android.gms:play-services-ads:25.5.0'
    implementation 'com.google.guava:guava:33.4.0-android'
    implementation project(':renderscript-toolkit')
    implementation platform('com.google.firebase:firebase-bom:34.19.0')

    // Declare the dependencies for the Crashlytics and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'
}
repositories {
    mavenCentral()
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'